[package]
name = "rsa_encrypt_pkcs1v15_message"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sidefuzz = "0.1.2"
rsa = "0.2.0"
rand_chacha = "0.2.2"
lazy_static = "1.4.0"