[package]
name = "num_bigint_dig_from_bytes_be"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sidefuzz = {git = "https://github.com/phayes/sidefuzz"}
num-bigint-dig = "0.4.0"