[package]
name = "blake3_reference_impl"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
sidefuzz = "0.1.2"
reference_impl = { git = "https://github.com/BLAKE3-team/BLAKE3"}
